package dev.pocketpal.local;
import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 static final int PICK=7001,LOG=7002;final int BG=0xff09090b,PANEL=0xff121215,PANEL2=0xff19191d,TEXT=0xfff1f1f3,MUTED=0xff9797a0;
 FrameLayout root,drawer;LinearLayout content,chatList,drawerList,composer,live;ScrollView scroll;TextView emptyTitle,emptyText,status,liveText;EditText input;ImageButton send;Button modelButton;
 boolean loaded,generating,follow=true,thinkingClosed;File modelFile,logFile;final Handler h=new Handler(Looper.getMainLooper());final StringBuilder raw=new StringBuilder();boolean posted,terminal;int assistant=-1;String lastAnswer="",lastThinking="";
 SharedPreferences prefs;final ArrayList<Chat> chats=new ArrayList<>();Chat current;int context=8192,threads=4,batchThreads=8,batch=512,maxTokens=1024,topK=40;float temperature=.7f,topP=.95f,minP=.05f;long seed=-1;boolean useJinja=true,enableThinking=true,flashAttention=true,mmap=true,mlock=false;String systemPrompt="";
 static class Msg{String r,c,t;Msg(String a,String b,String d){r=a;c=b;t=d==null?"":d;}}static class Chat{String id,title;ArrayList<Msg> m=new ArrayList<>();Chat(String i,String t){id=i;title=t;}}
 static final float UI_SCALE=.80f; int dp(float x){return(int)(x*getResources().getDisplayMetrics().density*UI_SCALE+.5f);}TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z*UI_SCALE);t.setTextColor(c);return t;}android.graphics.drawable.GradientDrawable bg(int c,float r){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setBackground(bg(0xffe8e8ec,24));b.setTextColor(0xff0f0f11);return b;}ImageButton ib(int r,String d){ImageButton b=new ImageButton(this);b.setImageResource(r);b.setContentDescription(d);b.setBackgroundColor(Color.TRANSPARENT);b.setPadding(dp(10),dp(10),dp(10),dp(10));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);initLog();prefs=getSharedPreferences("pocketpal_chats",0);loadChats();ui();render();}
 void initLog(){try{File x=getExternalFilesDir(null);if(x==null)x=getFilesDir();File d=new File(x,"logs");d.mkdirs();logFile=new File(d,"pocketpal_diagnostics.log");log("=== SESSION START ===");NativeBridge.nativeSetLogPath(logFile.getAbsolutePath());if(Build.VERSION.SDK_INT>=30)new Thread(()->{try{List<ApplicationExitInfo> e=((ActivityManager)getSystemService(ACTIVITY_SERVICE)).getHistoricalProcessExitReasons(getPackageName(),0,10);if(!e.isEmpty()){ApplicationExitInfo i=e.get(0);if(i.getReason()==ApplicationExitInfo.REASON_CRASH_NATIVE||i.getReason()==ApplicationExitInfo.REASON_CRASH||i.getReason()==ApplicationExitInfo.REASON_ANR)log("PREVIOUS_EXIT reason="+i.getReason()+" status="+i.getStatus()+" description="+i.getDescription());}}catch(Throwable t){}}).start();}catch(Throwable t){}}synchronized void log(String s){try{if(logFile==null)return;try(FileOutputStream o=new FileOutputStream(logFile,true)){o.write(("["+System.currentTimeMillis()+"] "+s+"\n").getBytes(StandardCharsets.UTF_8));}}catch(Throwable t){}}void exportLog(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"pocketpal_diagnostics.txt");startActivityForResult(i,LOG);}
 void ui(){root=new FrameLayout(this);root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets sys=in.getInsets(android.view.WindowInsets.Type.systemBars());android.graphics.Insets ime=in.getInsets(android.view.WindowInsets.Type.ime());int top=sys.top;int bottom=Math.max(sys.bottom,ime.bottom);content.setPadding(0,top,0,bottom);return in;});content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setBackgroundColor(BG);root.addView(content,new FrameLayout.LayoutParams(-1,-1));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);ImageButton m=ib(R.drawable.ic_menu,"Chats");m.setOnClickListener(v->drawer(true));top.addView(m,new LinearLayout.LayoutParams(dp(52),dp(60)));TextView title=tv("Chat",25,TEXT);title.setTypeface(null,Typeface.BOLD);top.addView(title,new LinearLayout.LayoutParams(0,dp(60),1));ImageButton n=ib(R.drawable.ic_edit,"New chat");n.setOnClickListener(v->newChat());top.addView(n,new LinearLayout.LayoutParams(dp(48),dp(60)));ImageButton set=ib(R.drawable.ic_more,"Settings");set.setOnClickListener(v->settings());top.addView(set,new LinearLayout.LayoutParams(dp(48),dp(60)));content.addView(top,new LinearLayout.LayoutParams(-1,dp(66)));
 LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),0,dp(18),0);emptyTitle=tv("Activate Model To Get Started",24,TEXT);emptyTitle.setGravity(Gravity.CENTER);body.addView(emptyTitle,new LinearLayout.LayoutParams(-1,dp(42)));emptyText=tv("Select the model and load it. After loading, start chatting with your local model.",17,MUTED);emptyText.setGravity(Gravity.CENTER);body.addView(emptyText,new LinearLayout.LayoutParams(-1,dp(90)));modelButton=btn("Select Model");modelButton.setOnClickListener(v->pickModel());body.addView(modelButton,new LinearLayout.LayoutParams(-1,dp(56)));scroll=new ScrollView(this);chatList=new LinearLayout(this);chatList.setOrientation(LinearLayout.VERTICAL);chatList.setPadding(0,dp(8),0,dp(20));scroll.addView(chatList);scroll.setVisibility(View.GONE);scroll.setOnScrollChangeListener((v,x,y,ox,oy)->{int d=scroll.getChildAt(0).getBottom()-(scroll.getHeight()+y);follow=d<dp(96);});body.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));content.addView(body,new LinearLayout.LayoutParams(-1,0,1));
 composer=new LinearLayout(this);composer.setOrientation(LinearLayout.VERTICAL);composer.setPadding(dp(14),dp(8),dp(14),dp(12));composer.setBackground(bg(PANEL,26));live=liveCard();live.setVisibility(View.GONE);composer.addView(live,new LinearLayout.LayoutParams(-1,dp(92)));input=new EditText(this);input.setHint("Type a message...");input.setHintTextColor(0xff696972);input.setTextColor(TEXT);input.setTextSize(17);input.setMinLines(2);input.setMaxLines(5);input.setGravity(Gravity.TOP|Gravity.START);input.setBackgroundColor(Color.TRANSPARENT);composer.addView(input,new LinearLayout.LayoutParams(-1,dp(66)));LinearLayout actions=new LinearLayout(this);actions.addView(ib(R.drawable.ic_plus,"Attach"),new LinearLayout.LayoutParams(dp(46),dp(42)));status=tv("Model not loaded",12,MUTED);actions.addView(status,new LinearLayout.LayoutParams(0,dp(42),1));send=ib(R.drawable.ic_send,"Send");send.setOnClickListener(v->{if(generating)NativeBridge.nativeStop();else send();});actions.addView(send,new LinearLayout.LayoutParams(dp(52),dp(42)));composer.addView(actions);content.addView(composer,new LinearLayout.LayoutParams(-1,dp(176)));buildDrawer();setContentView(root);}
 LinearLayout liveCard(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(12),dp(6),dp(12),dp(6));b.setBackground(bg(PANEL2,16));LinearLayout hrow=new LinearLayout(this);hrow.setGravity(Gravity.CENTER_VERTICAL);ImageView i=new ImageView(this);i.setImageResource(R.drawable.ic_brain);hrow.addView(i,new LinearLayout.LayoutParams(dp(24),dp(24)));TextView t=tv("Thinking",14,MUTED);t.setTypeface(null,Typeface.BOLD);hrow.addView(t,new LinearLayout.LayoutParams(0,dp(26),1));b.addView(hrow);liveText=tv("",13,MUTED);b.addView(liveText,new LinearLayout.LayoutParams(-1,dp(58)));return b;}
 void buildDrawer(){drawer=new FrameLayout(this);drawer.setVisibility(View.GONE);drawer.setBackgroundColor(0x99000000);drawer.setOnClickListener(v->drawer(false));root.addView(drawer,new FrameLayout.LayoutParams(-1,-1));LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(14),dp(22),dp(10),dp(12));p.setBackgroundColor(PANEL);drawer.addView(p,new FrameLayout.LayoutParams(dp(330),-1,Gravity.START));TextView t=tv("Chats",22,TEXT);t.setTypeface(null,Typeface.BOLD);p.addView(t,new LinearLayout.LayoutParams(-1,dp(48)));Button n=btn("New chat");n.setOnClickListener(v->newChat());p.addView(n,new LinearLayout.LayoutParams(-1,dp(48)));p.addView(tv("Saved chats",13,MUTED),new LinearLayout.LayoutParams(-1,dp(42)));ScrollView sv=new ScrollView(this);drawerList=new LinearLayout(this);drawerList.setOrientation(LinearLayout.VERTICAL);sv.addView(drawerList);p.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button s=btn("Settings");s.setOnClickListener(v->{drawer(false);settings();});p.addView(s,new LinearLayout.LayoutParams(-1,dp(48)));}
 void drawer(boolean x){drawer.setVisibility(x?View.VISIBLE:View.GONE);if(x)refreshDrawer();}
 void loadChats(){try{JSONArray a=new JSONArray(prefs.getString("json","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);Chat c=new Chat(o.optString("id"),o.optString("title","New chat"));JSONArray m=o.optJSONArray("messages");if(m!=null)for(int j=0;j<m.length();j++){JSONObject z=m.getJSONObject(j);c.m.add(new Msg(z.optString("role"),z.optString("content"),z.optString("thinking")));}chats.add(c);}}catch(Exception e){log("CHAT_LOAD_ERROR "+e);}current=find(prefs.getString("current",""));if(current==null)current=chats.isEmpty()?new Chat(UUID.randomUUID().toString(),"New chat"):chats.get(0);}
 Chat find(String id){for(Chat c:chats)if(c.id.equals(id))return c;return null;}void save(){try{if(current!=null){chats.remove(current);chats.add(0,current);}JSONArray a=new JSONArray();for(Chat c:chats){JSONObject o=new JSONObject();o.put("id",c.id);o.put("title",c.title);JSONArray m=new JSONArray();for(Msg x:c.m){JSONObject z=new JSONObject();z.put("role",x.r);z.put("content",x.c);z.put("thinking",x.t);m.put(z);}o.put("messages",m);a.put(o);}prefs.edit().putString("json",a.toString()).putString("current",current.id).apply();}catch(Exception e){log("CHAT_SAVE_ERROR "+e);}}
 void refreshDrawer(){drawerList.removeAllViews();for(Chat c:chats){TextView r=tv(c.title,15,TEXT);r.setPadding(dp(12),0,dp(8),0);r.setBackground(bg(c==current?PANEL2:PANEL,12));r.setOnClickListener(v->{if(generating)NativeBridge.nativeStop();current=c;save();render();drawer(false);});r.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle(c.title).setMessage("Delete this chat?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{chats.remove(c);if(c==current)current=new Chat(UUID.randomUUID().toString(),"New chat");save();render();refreshDrawer();}).show();return true;});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.bottomMargin=dp(6);drawerList.addView(r,lp);}}
 void newChat(){if(generating)NativeBridge.nativeStop();save();current=new Chat(UUID.randomUUID().toString(),"New chat");render();drawer(false);input.setText("");}
 void render(){chatList.removeAllViews();boolean has=false;for(int i=0;i<current.m.size();i++){Msg m=current.m.get(i);if(m.r.equals("user")){has=true;TextView u=tv("You",13,MUTED);u.setTypeface(null,Typeface.BOLD);chatList.addView(u);TextView p=tv("",16,TEXT);p.setText(MarkdownRenderer.render(m.c));p.setGravity(Gravity.TOP|Gravity.START);chatList.addView(p);}else{has=true;if(!m.t.isEmpty()&&(!(generating&&i==assistant)||thinkingClosed))chatList.addView(thinkingCard(m.t));TextView a=tv("",16,TEXT);a.setGravity(Gravity.TOP|Gravity.START);a.setText(MarkdownRenderer.render(m.c));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(20);chatList.addView(a,lp);}}scroll.setVisibility(has?View.VISIBLE:View.GONE);emptyTitle.setVisibility(has?View.GONE:View.VISIBLE);emptyText.setVisibility(has?View.GONE:View.VISIBLE);modelButton.setVisibility(has?View.GONE:View.VISIBLE);if(has&&follow)scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));refreshDrawer();}
 LinearLayout thinkingCard(String v){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(10),dp(7),dp(10),dp(7));b.setBackground(bg(PANEL2,14));LinearLayout hrow=new LinearLayout(this);hrow.setGravity(Gravity.CENTER_VERTICAL);ImageView i=new ImageView(this);i.setImageResource(R.drawable.ic_brain);hrow.addView(i,new LinearLayout.LayoutParams(dp(22),dp(22)));TextView title=tv("Thinking  >",13,MUTED);title.setTypeface(null,Typeface.BOLD);hrow.addView(title,new LinearLayout.LayoutParams(0,dp(28),1));b.addView(hrow);TextView body=tv("",13,MUTED);body.setText(MarkdownRenderer.render(v));body.setVisibility(View.GONE);b.addView(body);hrow.setOnClickListener(x->{boolean o=body.getVisibility()!=View.VISIBLE;body.setVisibility(o?View.VISIBLE:View.GONE);title.setText(o?"Thinking  v":"Thinking  >");});return b;}
 void send(){if(!loaded||generating)return;String p=input.getText().toString().trim();if(p.isEmpty())return;if(current.m.isEmpty())current.title=p.length()>42?p.substring(0,42):p;current.m.add(new Msg("user",p,""));current.m.add(new Msg("assistant","",""));assistant=current.m.size()-1;save();input.setText("");generating=true;follow=true;thinkingClosed=false;raw.setLength(0);posted=terminal=false;live.setVisibility(View.GONE);send.setImageResource(R.drawable.ic_stop);render();ArrayList<String> rr=new ArrayList<>(),cc=new ArrayList<>();for(int i=0;i<current.m.size()-1;i++){Msg m=current.m.get(i);rr.add(m.r);cc.add(m.c);}new Thread(()->{boolean ok=NativeBridge.nativeGenerateChat(rr.toArray(new String[0]),cc.toArray(new String[0]),maxTokens,temperature,topP,topK,minP,seed,useJinja,enableThinking,systemPrompt,(piece,done)->{if(piece!=null&&!piece.isEmpty())synchronized(raw){raw.append(piece);}if(!posted){posted=true;h.postDelayed(()->{posted=false;if(!terminal)stream();},50);}});log("JAVA nativeGenerateChat RETURN ok="+ok);h.post(()->{if(terminal)return;terminal=true;finishGen();});}).start();}
 void stream(){try{String s;synchronized(raw){s=raw.toString();}ThinkingParser.Parts p=ThinkingParser.split(s);lastThinking=p.thinking;lastAnswer=p.answer;if(p.active){thinkingClosed=false;live.setVisibility(View.VISIBLE);liveText.setText(p.thinking);}else if(!p.thinking.isEmpty()){thinkingClosed=true;live.setVisibility(View.GONE);}else live.setVisibility(View.GONE);Msg a=current.m.get(assistant);a.t=p.thinking;a.c=p.answer;render();}catch(Throwable t){log("STREAM_UI_ERROR "+android.util.Log.getStackTraceString(t));}}
 void finishGen(){try{String s;synchronized(raw){s=raw.toString();}ThinkingParser.Parts p=ThinkingParser.split(s);lastThinking=p.thinking;lastAnswer=p.answer;Msg a=current.m.get(assistant);a.t=p.thinking;a.c=p.answer;live.setVisibility(View.GONE);thinkingClosed=true;generating=false;save();render();send.setImageResource(R.drawable.ic_send);}catch(Throwable t){log("FINISH_UI_ERROR "+android.util.Log.getStackTraceString(t));generating=false;send.setImageResource(R.drawable.ic_send);}}
 void copy(){if(lastAnswer.isEmpty())return;((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("assistant",lastAnswer));}
 void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q==LOG&&r==RESULT_OK&&d!=null){try(InputStream in=new FileInputStream(logFile);OutputStream out=getContentResolver().openOutputStream(d.getData())){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}catch(Exception e){}return;}if(q!=PICK||r!=RESULT_OK||d==null)return;Uri u=d.getData();new Thread(()->{try{File dir=new File(getFilesDir(),"models");dir.mkdirs();String n=name(u);modelFile=new File(dir,n);try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream out=new FileOutputStream(modelFile)){byte[] b=new byte[1024*1024];int n2;while((n2=in.read(b))>0)out.write(b,0,n2);}runOnUiThread(this::loadModel);}catch(Exception e){}}).start();}
 String name(Uri u){try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst())return c.getString(i);}catch(Exception e){}return "model.gguf";}
 void loadModel(){modelButton.setEnabled(false);modelButton.setText("Loading model…");new Thread(()->{boolean ok=NativeBridge.nativeLoad(modelFile.getAbsolutePath(),context,threads,batchThreads,batch,flashAttention,mmap,mlock);runOnUiThread(()->{loaded=ok;modelButton.setEnabled(true);modelButton.setText(ok?"Model Loaded":"Select Model");status.setText(ok?modelFile.getName():"Model load failed");});}).start();}
 void settings(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(4),dp(18),dp(4));ScrollView sv=new ScrollView(this);sv.addView(b);
EditText ctx=settingInt("Context",context);b.addView(ctx);EditText th=settingInt("Generation threads",threads);b.addView(th);EditText bth=settingInt("Prompt threads",batchThreads);b.addView(bth);EditText bat=settingInt("Batch size",batch);b.addView(bat);EditText mt=settingInt("Max output tokens",maxTokens);b.addView(mt);EditText tk=settingInt("Top K",topK);b.addView(tk);EditText temp=settingFloat("Temperature",temperature);b.addView(temp);EditText tp=settingFloat("Top P",topP);b.addView(tp);EditText mp=settingFloat("Min P",minP);b.addView(mp);
EditText sys=new EditText(this);sys.setHint("System prompt (optional)");sys.setText(systemPrompt);sys.setTextColor(TEXT);sys.setHintTextColor(MUTED);sys.setMinLines(2);sys.setGravity(Gravity.TOP);b.addView(sys);
CheckBox think=check("Enable thinking / reasoning",enableThinking);b.addView(think);CheckBox flash=check("Flash Attention",flashAttention);b.addView(flash);CheckBox mm=check("Memory map model",mmap);b.addView(mm);CheckBox ml=check("Lock model in RAM",mlock);b.addView(ml);CheckBox j=check("Use Jinja chat templates",useJinja);b.addView(j);Button e=btn("Export diagnostic log");e.setOnClickListener(v->exportLog());b.addView(e);
new AlertDialog.Builder(this).setTitle("Local model settings").setView(sv).setPositiveButton("Apply",(d,w)->{try{context=Math.max(512,Integer.parseInt(ctx.getText().toString()));threads=Math.max(1,Integer.parseInt(th.getText().toString()));batchThreads=Math.max(1,Integer.parseInt(bth.getText().toString()));batch=Math.max(32,Integer.parseInt(bat.getText().toString()));maxTokens=Math.max(1,Integer.parseInt(mt.getText().toString()));topK=Math.max(0,Integer.parseInt(tk.getText().toString()));temperature=Float.parseFloat(temp.getText().toString());topP=Float.parseFloat(tp.getText().toString());minP=Float.parseFloat(mp.getText().toString());}catch(Exception ignored){}systemPrompt=sys.getText().toString();enableThinking=think.isChecked();flashAttention=flash.isChecked();mmap=mm.isChecked();mlock=ml.isChecked();useJinja=j.isChecked();}).setNegativeButton("Cancel",null).show();}
EditText settingInt(String hint,int v){EditText e=new EditText(this);e.setHint(hint);e.setText(String.valueOf(v));e.setInputType(2);e.setTextColor(TEXT);e.setHintTextColor(MUTED);return e;}
EditText settingFloat(String hint,float v){EditText e=new EditText(this);e.setHint(hint);e.setText(String.valueOf(v));e.setInputType(2|8192);e.setTextColor(TEXT);e.setHintTextColor(MUTED);return e;}
CheckBox check(String s,boolean v){CheckBox c=new CheckBox(this);c.setText(s);c.setTextColor(TEXT);c.setChecked(v);return c;}
 @Override protected void onDestroy(){log("=== SESSION DESTROY ===");save();if(generating)NativeBridge.nativeStop();h.removeCallbacksAndMessages(null);NativeBridge.nativeFree();super.onDestroy();}
}